name: easy_dio_client
description: A lightweight Dio-based HTTP client for Flutter with authentication, token refresh, file upload/download, and generic model conversion support.

version: 0.0.3
homepage: https://github.com/abimbola-michael/easy_dio_client
repository: https://github.com/abimbola-michael/easy_dio_client
issue_tracker: https://github.com/abimbola-michael/easy_dio_client/issues

license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  flutter_secure_storage: ^10.0.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
